# Exemplo de parâmetros para a navegação
amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2


controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0


planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True


